//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace readShorts.ManageBackoffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUShortShareType
    {
        public string Description { get; set; }
        public long RecordKey { get; set; }
        public string Description_Herew { get; set; }
    }
}
