//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace readShorts.ManageBackoffice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class readShorts_DB_DEVEntities : DbContext
    {
        public readShorts_DB_DEVEntities()
            : base("name=readShorts_DB_DEVEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ad> Ad { get; set; }
        public virtual DbSet<Short> Short { get; set; }
        public virtual DbSet<ShortChannel> ShortChannel { get; set; }
        public virtual DbSet<ShortTag> ShortTag { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<LUActivity> LUActivity { get; set; }
        public virtual DbSet<LUCountry> LUCountry { get; set; }
        public virtual DbSet<LUEventType> LUEventType { get; set; }
        public virtual DbSet<LUGender> LUGender { get; set; }
        public virtual DbSet<LUGroup> LUGroup { get; set; }
        public virtual DbSet<LUPointType> LUPointType { get; set; }
        public virtual DbSet<LUShortAgeRestriction> LUShortAgeRestriction { get; set; }
        public virtual DbSet<LUShortChannelType> LUShortChannelType { get; set; }
        public virtual DbSet<LUShortReportType> LUShortReportType { get; set; }
        public virtual DbSet<LUShortShareType> LUShortShareType { get; set; }
        public virtual DbSet<LUShortTagType> LUShortTagType { get; set; }
        public virtual DbSet<LUSubscriptionType> LUSubscriptionType { get; set; }
        public virtual DbSet<LUSysInterfaceLanguage> LUSysInterfaceLanguage { get; set; }
        public virtual DbSet<LUUserStatus> LUUserStatus { get; set; }
    }
}
