//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace readShorts.ManageBackoffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShortChannel
    {
        public long RecordKey { get; set; }
        public long ShortKey { get; set; }
        public System.DateTime CreatedTimeStamp { get; set; }
        public int CreatedUserKey { get; set; }
        public System.DateTime LastUpdateTimeStamp { get; set; }
        public int LastUpdateUserKey { get; set; }
        public bool IsRowDeleted { get; set; }
        public long LUShortChannelTypeKey { get; set; }
    }
}
