//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace readShorts.ManageBackoffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Short
    {
        public long RecordKey { get; set; }
        public string PicturePath { get; set; }
        public string Quote { get; set; }
        public string Text { get; set; }
        public string FooterText { get; set; }
        public string FooterLink { get; set; }
        public decimal ERT { get; set; }
        public System.DateTime CreatedTimeStamp { get; set; }
        public int CreatedUserKey { get; set; }
        public System.DateTime LastUpdateTimeStamp { get; set; }
        public int LastUpdateUserKey { get; set; }
        public bool IsRowDeleted { get; set; }
        public long LUShortAgeRestrictionKey { get; set; }
        public string Title { get; set; }
        public string VideoPath { get; set; }
        public string Embed { get; set; }
        public bool IsPublic { get; set; }
        public bool IsDraft { get; set; }
        public long WriterUserKey { get; set; }
        public long LUSysInterfacelanguageKey { get; set; }
    }
}
