//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace readShorts.ManageBackoffice
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public long RecordKey { get; set; }
        public string UserSecurityNumber { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HashedPassword { get; set; }
        public string ClientIP { get; set; }
        public string EmailAddress { get; set; }
        public string MobileSerialNumber { get; set; }
        public System.DateTime LastActitiyDate { get; set; }
        public bool IsAnonimousConnect { get; set; }
        public bool IsFBConnect { get; set; }
        public bool IsTWConnect { get; set; }
        public bool IsGGLConnect { get; set; }
        public bool IsEmailConnect { get; set; }
        public System.DateTime CreatedTimeStamp { get; set; }
        public int CreatedUserKey { get; set; }
        public System.DateTime LastUpdateTimeStamp { get; set; }
        public int LastUpdateUserKey { get; set; }
        public bool IsRowDeleted { get; set; }
        public long LUSubscriptionTypeKey { get; set; }
        public string ShortBio { get; set; }
        public long LUSysInterfacelanguageKey { get; set; }
    }
}
